# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rubygsm}
  s.version = "0.42.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Adam Mckaig}, %q{Liehann Loots}]
  s.date = %q{2011-08-26}
  s.email = [%q{adam.mckaig@gmail.com}, %q{liehannl@gmail.com}]
  s.executables = [%q{gsm-modem-band}, %q{sms}]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".watchr",
    "Gemfile",
    "Gemfile.lock",
    "README.rdoc",
    "Rakefile",
    "bin/gsm-modem-band",
    "bin/sms",
    "lib/rubygsm.rb",
    "lib/rubygsm/core.rb",
    "lib/rubygsm/errors.rb",
    "lib/rubygsm/log.rb",
    "lib/rubygsm/msg/incoming.rb",
    "lib/rubygsm/msg/outgoing.rb",
    "rubygsm.gemspec",
    "spec/mock/modem.rb",
    "spec/modem_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/adammck/rubygsm}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Send and receive SMS with a GSM modem}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<toholio-serialport>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<watchr>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<toholio-serialport>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.6"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<watchr>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<toholio-serialport>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.6"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<watchr>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

